# Generated by Django 3.0.4 on 2020-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email_reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email_reply_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
