# Generated by Django 3.0.4 on 2020-04-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_feedback_email_reply_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email_reply_adress',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email_reply_time',
        ),
    ]
